######################################################################
# Automatically generated by qmake (2.01a) Sat Mar 13 15:10:19 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . ../
INCLUDEPATH += . ../
LIBS += -L../ -lkeduvocdocument
QT += core testlib
CONFIG +=qtestlib

# Input
SOURCES += tests.cpp
