######################################################################
# Automatically generated by qmake (2.01a) Sat Mar 13 15:10:19 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . ../
INCLUDEPATH += . ../
LIBS += -L../ -lqtvtvocdocument
QT += core testlib
CONFIG += qtestlib

QMAKE_LFLAGS += -Wl,-rpath,../

# Input
SOURCES += tests.cpp
